version: "3.8"

services:
  dev_client_np:
    container_name: dev_client_np
    build:
      context: ../client/
      dockerfile: dev.Dockerfile
      no_cache: true
    image: "dev_client_np"
    volumes:
      - ../client/:/app/
    env_file:
      - ../client/configs/.env.dev
    networks:
      - dev-np-net
    expose:
      - 3000
    restart: unless-stopped

  dev_nginx_np:
    depends_on:
      - dev_client_np
    container_name: dev_nginx_np
    image: "nginx:latest"
    volumes:
      - ../dev-ops/nginx/conf.dev.d/:/etc/nginx/conf.d/
    ports:
      - "100:80"
    networks:
      - dev-np-net
    restart: unless-stopped

networks:
  dev-np-net:
    external: true
